name: server update with new repo code

concurrency: 
  group: production
  cancel-in-progress: true
  
on:
  push:
      branches: [ main ]
jobs:
  pulling:
    name: pulling from repo
    runs-on: self-hosted

    steps:
      - name: pull repo
        run: cd /Back/front; git pull;
        
  build-vite:
    name: build project
    runs-on: self-hosted

    steps:
      - name: npm start build
        run: cd /Back/front; npm start build;
